[package]
name = "mandelbrot-explorer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.24.7"
dotenv = "0.15.0"
rug = "1.17"
