name: Deploy

on:
  push:
    tags: [v-*]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: echo $"${{ secrets.DOTENV }}" > .env
      - name: Build
        run: cargo build --verbose --release
      - name: Execute
        run: cargo run --release
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg
      - name: Convert to mp4
        run: ffmpeg -r 30 -i ./dist/%08d.png -vcodec libx264 -pix_fmt yuv420p -r 60 ./fruit.mp4
      - name: Move artifact
        run: mv ./fruit.mp4 ./public/fruit.mp4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
